# Based on the build and push docker image action on the github actions marketplace
# This uses path context to make use of the .dockerignore file. See the path context section at
# https://github.com/marketplace/actions/build-and-push-docker-images
name: Build Node-Based Docker Image

on:
  push:
    branches: 'auto-build'

jobs:
  Build and Push Image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/remote-portfolio:latest
            ${{ vars.DOCKER_REGISTRY }}/remote-portfolio:1.0.0
